name: "Matter Code Vault"
version: "2.22.7"
slug: "matter_code_vault"
description: "Matter 기기 관리 및 QR 코드 백업/복원 도구입니다."
url: "https://github.com/dicapriokim/Matter-Code-Vault"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
map:
  - config:rw
  - share:rw
options:
  api_key: ""
schema:
  api_key: str?
# image: "matter-code-vault-{arch}"
ingress: true
ingress_port: 8099
panel_icon: mdi:qrcode-scan
webui: http://[HOST]:[PORT:8099]/
